USE [master]
GO

/****** Object:  Database [Family_Database]    Script Date: 31-Dec-15 10:43:54 AM ******/
CREATE DATABASE [Family_Database]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Family_Database', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Family_Database.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Family_Database_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Family_Database_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Family_Database] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Family_Database].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Family_Database] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Family_Database] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Family_Database] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Family_Database] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Family_Database] SET ARITHABORT OFF 
GO

ALTER DATABASE [Family_Database] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Family_Database] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Family_Database] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Family_Database] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Family_Database] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Family_Database] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Family_Database] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Family_Database] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Family_Database] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Family_Database] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Family_Database] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Family_Database] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Family_Database] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Family_Database] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Family_Database] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Family_Database] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Family_Database] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Family_Database] SET RECOVERY FULL 
GO

ALTER DATABASE [Family_Database] SET  MULTI_USER 
GO

ALTER DATABASE [Family_Database] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Family_Database] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Family_Database] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Family_Database] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Family_Database] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Family_Database] SET  READ_WRITE 
GO


